### ISSUE TITLE
Exception "ctor must be called on the UI thread" during startup

### ISSUE THREAD

**Issue by AlonAm** [VsixCommunity/Community.VisualStudio.Toolkit.DependencyInjection#10]
**Version**

17.0.13

**Description**

Error ".ctor must be called on the UI thread" occurs when the package loads in the background.

**Analysis**

The base package class [DIToolkitPackage](https://github.com/VsixCommunity/Community.VisualStudio.Toolkit.DependencyInjection/blob/ee9b1ad6f0329b3b74eafae6c11aa8b1ca1e0c51/src/Core/Shared/DIToolkitPackage.cs#L59C16-L59C17) creates instances of [CommandWrapper<>]() during InitializeAsync.
The class CommandWrapper calls IMenuCommandService.AddCommand in the constructor, which requires the main UI thread.     

**ActivityLog.xml**

SetSite failed for package [DatadogPackage]Source: &apos;Microsoft.VisualStudio.Shell.Framework&apos; Description: .ctor must be called on the UI thread.&#x000D;&#x000A;System.Runtime.InteropServices.COMException (0x8001010E): .ctor must be called on the UI thread.&#x000D;&#x000A;   at Microsoft.VisualStudio.Shell.ThreadHelper.ThrowIfNotOnUIThread(String callerMemberName)&#x000D;&#x000A;   at Community.VisualStudio.Toolkit.DependencyInjection.Core.CommandWrapper`1..ctor(IServiceProvider serviceProvider, AsyncPackage package)&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()&#x000D;&#x000A;   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)&#x000D;&#x000A;   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)&#x000D;&#x000A;   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)&#x000D;&#x000A;   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)&#x000D;&#x000A;   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)&#x000D;&#x000A;   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(Type serviceType)&#x000D;&#x000A;   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)&#x000D;&#x000A;   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)&#x000D;&#x000A;   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)&#x000D;&#x000A;   at Community.VisualStudio.Toolkit.DependencyInjection.DIToolkitPackage`1.&lt;InitializeAsync&gt;d__0.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;   at Datadog.VisualStudio.Extension.VS2022.DatadogPackage.&lt;InitializeAsync&gt;d__24.MoveNext() in D:\a\1\s\src\Datadog.VisualStudio.Extension.VS2022\DatadogPackage.cs:line 41&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;   at Microsoft.VisualStudio.Shell.AsyncPackage.&lt;&gt;c__DisplayClass21_0.&lt;&lt;Microsoft-VisualStudio-Shell-Interop-IAsyncLoadablePackageInitialize-Initialize&gt;b__1&gt;d.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()&#x000D;&#x000A;   at Microsoft.VisualStudio.Services.VsTask.RethrowException(AggregateException e)&#x000D;&#x000A;   at Microsoft.VisualStudio.Services.VsTask.InternalGetResult(Boolean ignoreUIThreadCheck)

**Comment by AlonAm** [comment]
This line looks related: https://github.com/VsixCommunity/Community.VisualStudio.Toolkit.DependencyInjection/blob/ee9b1ad6f0329b3b74eafae6c11aa8b1ca1e0c51/src/Core/Shared/CommandWrapper.cs#L37C13-L37C49

**Comment by madskristensen** [comment]
Adding commands have to happen on the UI thread as the exception points out. You can switch to the UI thread as you stated, and that should work. For your specific case, I'll let @StevenRasmussen comment if there's anything of interest for the DI system here

**Comment by AlonAm** [comment]
As a temporary solution to avoid the error message, is it better to add `await JoinableTaskFactory.SwitchToMainThreadAsync();` before the `await base.InitializeAsync(cancellationToken, progress);`?

**Comment by StevenRasmussen** [comment]
Sorry for the delay in responding. Just approved and merged the PR.  Thanks!

**Comment by AlonAm** [comment]
Thanks you for your help! 🙂
