### ISSUE TITLE
Publish packages to NuGet

### ISSUE THREAD

**Issue by StevenRasmussen** [VsixCommunity/Community.VisualStudio.Toolkit.DependencyInjection#2]
@madskristensen - Any chance you can help with getting the CI/CD process setup for this repo so that packages are produced/published to NuGet?

**Comment by madskristensen** [comment]
yup, i can do that part

**Comment by StevenRasmussen** [comment]
@madskristensen - bump ;)  Thanks

**Comment by madskristensen** [comment]
Yikes, sorry I forgot. I'll take a look soon, but currently out on leave

**Comment by StevenRasmussen** [comment]
No worries.  Just wanted to keep it on your radar 😃

**Comment by StevenRasmussen** [comment]
Hi @madskristensen - Just following up on this. Thanks!

**Comment by madskristensen** [comment]
Would it make sense if the package inherited from TookitPackage?

**Comment by StevenRasmussen** [comment]
It would... and it does 😃 . See [here](https://github.com/VsixCommunity/Community.VisualStudio.Toolkit.DependencyInjection/blob/3f4673d8147080ac226e7e210e0d7202c70a6ba8/src/Core/Shared/DIToolkitPackage.cs#L15).

**Comment by madskristensen** [comment]
It's now publishing to NuGet. There are output warnings about no content in the 'lib' folder and I also noticed that it isn't referencing the latest Toolkit packages (should use Community.VisualStudio.Toolkit.<version>.

[See build details here: https://ci.appveyor.com/project/madskristensen/community-visualstudio-toolkit-dependencyinjection](https://ci.appveyor.com/project/madskristensen/community-visualstudio-toolkit-dependencyinjection/builds/42247665)

**Comment by StevenRasmussen** [comment]
Awesome!  I'll take a look at those issues.  Also, it looks like it would probably be a good idea to follow the same naming convention and NuGet publishing strategy as the main toolkit, ie:

`Community.VisualStudio.Toolkit.DependencyInjection.Core.14`
`Community.VisualStudio.Toolkit.DependencyInjection.Core.15`
... and
`Community.VisualStudio.Toolkit.DependencyInjection.Microsoft.14`
`Community.VisualStudio.Toolkit.DependencyInjection.Microsoft.15`
...

I'll update the projects so that they are named correctly. Thanks again!
