### ISSUE TITLE
Guidelines for dependency injection in VS extensions

### ISSUE THREAD

**Issue by dybzon** [VsixCommunity/Community.VisualStudio.Toolkit.DependencyInjection#3]
Hi

I've recently started writing my first VS extension, and I've been struggling to find a good way to handle dependency injection. I come from the "web world" with .NET Core/ASP.NET Core where it's pretty much built in, and I can just declare my dependencies in the constructor of a controller class or similar. Assuming I've built a service container, of course. I was hoping I could do something similar in my VS extension.

Do you know of any guidelines/documentation/good examples of how dependency injection can be set up and used in a VS extension?

Any pointers to helpful resources are greatly appreciated!

**Comment by StevenRasmussen** [comment]
Hi @dybzon - I have updated the `ReadMe` to include information on how to use this package.

**Comment by dybzon** [comment]
Hi @StevenRasmussen , thanks for the update. That is exactly what I did after reading through the code, and it works great!

Are there any plans of adding support for other DI containers? Otherwise I'll probably look into writing a package for Autofac (similar to your `MicrosoftDIToolkitPackage`)

**Comment by StevenRasmussen** [comment]
There aren't any immediate plans for adding more DI containers, but it has definitely been architected with this in mind.  Feel free to submit a PR if you come up with something for Autofac.
