### ISSUE TITLE
Un-list the old Nuget packages

### ISSUE THREAD

**Issue by StevenRasmussen** [VsixCommunity/Community.VisualStudio.Toolkit.DependencyInjection#4]
@madskristensen - You may have noticed that I've updated the projects and resulting packages to follow the naming convention of the main project so that they append the major version of Visual Studio for which they apply, ie:
`Community.VisualStudio.Toolkit.DependencyInjection.Core.14`
`Community.VisualStudio.Toolkit.DependencyInjection.Core.15`
`Community.VisualStudio.Toolkit.DependencyInjection.Core.16`
`Community.VisualStudio.Toolkit.DependencyInjection.Core.17`

Would you be able to un-list the old packages on Nuget:
[Community.VisualStudio.Toolkit.DependencyInjection.Core](https://www.nuget.org/packages/Community.VisualStudio.Toolkit.DependencyInjection.Core/17.0.75.3-pre)
[Community.VisualStudio.Toolkit.DependencyInjection.Microsoft](https://www.nuget.org/packages/Community.VisualStudio.Toolkit.DependencyInjection.Microsoft/17.0.75.3-pre)

Thanks!

**Comment by madskristensen** [comment]
Done. I've marked the old ones deprecated
