### ISSUE TITLE
Can't acess BaseDICommand

### ISSUE THREAD

**Issue by davidterins** [VsixCommunity/Community.VisualStudio.Toolkit.DependencyInjection#6]
Hi, 

I am trying out the package _Community.VisualStudio.Toolkit.DependencyInjection.Microsoft.17_ version _17.0.6_ and I am not able to access the `BaseDICommand` needed to be able to setup commands using DI. 

![image](https://user-images.githubusercontent.com/25159662/159512104-9a636cf6-25d7-440e-a5d9-0796a27f2de5.png)

![image](https://user-images.githubusercontent.com/25159662/159513411-e1d10504-2a96-44a4-87aa-668deaa07e57.png)

Am I missing anything to be able to access it?

**Comment by StevenRasmussen** [comment]
@madskristensen - Just wanted to follow up on this to see if you had any thoughts. Thanks!

**Comment by madskristensen** [comment]
I'll release a new version of the main package now

**Comment by madskristensen** [comment]
It's been published and NuGet is indexing it now, so give it 10 minutes or so before it shows up

**Comment by davidterins** [comment]
Thank you, I will try it out as soon as i get a chance

**Comment by StevenRasmussen** [comment]
Thanks @madskristensen!  I have updated the references and pushed a [release] commit. Looks like they are in NuGet now.  @davidterins - You should be able to use version [X].0.13 of the packages and have access to the `BaseDICommand` now.
